package spark.etl.usecases.DroolsRuleEngineJDK8.Person

rule "Adult Rule"
when
    $person: Person(age >= 18)
then
//    $person.setAge($person.getAge() + 5);
    $person.age = 1000
//    modify($person) {
//        setAge($person.getAge() + 1)
//    }
end

rule "Senior Rule"
when
    $person: Person(age >= 60)
then
    $person.setAge($person.getAge() + 10);
    modify($person) {
        setAge($person.getAge() + 2)
    }
end

rule "always Rule"
when
    $person: Person(age >= 0)
then
    $person.setAge($person.getAge() + 10);
    modify($person) {
        setAge($person.getAge() + 2)
    }
end
